### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by future4772** [quentn69/TikTok-Generator-Checker#3]
HI
PLEASE HOW CAN I MAKE INSTAGRAM AND TIKTOK 3L/4L USERNAME
PLEASEEEEEEEEE HELP ME
THANK YOU

**Comment by quentn69** [comment]
If you want to change your name on Instagram = Go to you profile, click on edit profile and enter your new username.
If you want to change your name on   TikTok     = Go to you profile, click on edit profile and enter your new username.

If that doesn't work, someone else already has the username or it is blacklisted.
